- name: Demo on facts
  hosts: all
  ##gather_facts: no  if you dont need facts to be gathered we can mention has "no"
  
  tasks: 
     - name: Printing the default variable
       ansible.builtin.debug:
        msg: server flavour is {{ansible_distribution}}


  tasks: 
     - name: Printing the macaddress
       ansible.builtin.debug:
        msg: Mac address of the machine is {{ansible_default_ipv4.macaddress}}