- name: Demo on conditions
  hosts: all
  vars:
    action: false       
  tasks: 
    - name: Run this only when distribution is centOS
      ansible.builtin.debug:
        mes: Welcome to {{ansible_distribution}}
      when: ansible_distribution == "centOS"

    - name: Run this only when distribution is Ubuntu
      ansible.builtin.debug:
        mes: Welcome to {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"   

    - name: Run this action
      ansible.builtin.debug:
        mes: Action is true
      when: action

    - name: Run this task when the variable is declared
      ansible.builtin.debug:
        mes: Action is variable is declared
      when: action is not defined