- name: Demo on using tags
  hosts: all
  
  tasks: 
     - name: This is a frontend task
       ansible.builtin.debug:
        msg: Installing frontend
       tags: frontend 
    
     - name: starting frontend
       ansible.builtin.debug:
        msg: starting frontend
      tags: frontend 
      