- name: Demo on copy 
  hosts: all
  become: yes
  tasks:
    - name : copying the file from src to destination
      ansible.builtin.copy:
         src: systemd.service
         dest: /home/centos/systemd.service